version: '3'
services:
    db:
        image: kartoza/postgis:latest
        environment:
            - USERNAME=docker
            - PASSWORD=docker
            - POSTGRES_DBNAME=bourgs-centres
        volumes:
            - ./Docker/postgres_data:/var/lib/postgresql

    server:
        image: camptocamp/qgis-server:3.12
        hostname: qgis-server
        volumes:
            - /home/qgis/projects/bourgs-centres:/etc/qgisserver
        environment:
            - QGIS_SERVER_LOG_LEVEL=0
        links:
          - db:db
        ports:
            - 8080:80

    qgis:
        image: qgis/qgis:release-3_12
        environment:
            - DISPLAY=unix$DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /home/qgis/projects/bourgs-centres:/project
        links:
          - db:db
        command: ["qgis", "/project/project.qgs"]