version: '3'
services:
    db:
        image: kartoza/postgis:latest
        environment:
            - USERNAME=docker
            - PASSWORD=docker
            - POSTGRES_DBNAME=bourgs-centres
        volumes:
            - ./Docker/postgres_data:/var/lib/postgresql
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4:4.20
        environment:
            - PGADMIN_DEFAULT_EMAIL=hugo.jahnke@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=password
        ports:
            - 8888:80
        links:
            - db:db
